---
hb_base_url: "https://100.123.0.19:8080/api/v1/"
user: "jcluser"
password: "Juniper!1"
devices_body: "{{ lookup('file','devices.json') }}"
rules_body: "{{ lookup('file','rules.json') }}"
playbooks_body: "{{ lookup('file','playbooks.json') }}"
notifications_body: "{{ lookup('file','notifications.json') }}"
device_groups_body: "{{ lookup('file','device-groups.json') }}"
network_groups_body: "{{ lookup('file','network-groups.json') }}"
